-- MySQL Script generated by MySQL Workbench
-- Thu Nov 16 22:06:20 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cheftable
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS cheftable ;

-- -----------------------------------------------------
-- Schema cheftable
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS cheftable DEFAULT CHARACTER SET utf8 ;
USE cheftable ;

-- -----------------------------------------------------
-- Table `cheftable`.`Cierre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Cierre (
  Codigo INT NOT NULL AUTO_INCREMENT,
  valor_cierre INT NOT NULL,
  Fecha DATE NOT NULL,
  PRIMARY KEY (Codigo))
ENGINE = InnoDB;

describe Cierre;


-- -----------------------------------------------------
-- Table `cheftable`.`Plato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Plato (
  idPlato INT NOT NULL AUTO_INCREMENT,
  Tipo_Menu VARCHAR(45) NOT NULL,
  PRIMARY KEY (idPlato))
ENGINE = InnoDB;

describe Plato;


-- -----------------------------------------------------
-- Table `cheftable`.`Comanda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Comanda (
  idComanda INT NOT NULL AUTO_INCREMENT,
  NoMesa INT NOT NULL,
  referencia VARCHAR(45) NOT NULL,
  Descripcion_produc VARCHAR(45) NOT NULL,
  Adicionales VARCHAR(45) NOT NULL,
  Cantidad INT NOT NULL,
  Fecha DATE NOT NULL,
  Plato_idPlato INT NOT NULL,
  PRIMARY KEY (idComanda),
  CONSTRAINT fk_Comanda_Plato1
    FOREIGN KEY (Plato_idPlato)
    REFERENCES Plato (idPlato)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX fk_Comanda_Plato1_idx ON Comanda (Plato_idPlato ASC);


-- -----------------------------------------------------
-- Table `cheftable`.`Mesero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Mesero (
 idMesero INT NOT NULL AUTO_INCREMENT,
  nombreMes VARCHAR(45) NOT NULL,
  celular VARCHAR(45) NOT NULL,
  Password VARCHAR(45) NOT NULL,
  Cierre_Codigo INT NOT NULL,
  Comanda_idComanda INT NOT NULL,
  PRIMARY KEY (idMesero),
  CONSTRAINT fk_Mesero_Cierre1
    FOREIGN KEY (Cierre_Codigo)
    REFERENCES Cierre (Codigo)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_Mesero_Comanda1
    FOREIGN KEY (Comanda_idComanda)
    REFERENCES Comanda (idComanda)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX fk_Mesero_Cierre1_idx ON Mesero (Cierre_Codigo ASC);

CREATE INDEX fk_Mesero_Comanda1_idx ON Mesero (Comanda_idComanda ASC);
/*22:38:41	CREATE INDEX fk_Comanda_Plato1_idx ON Comanda (Plato_idPlato ASC) VISIBLE	Error Code: 1064. You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1	0.000 sec
*/


-- -----------------------------------------------------
-- Table `cheftable`.`Mesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Mesa (
  idMesa INT NOT NULL AUTO_INCREMENT,
  No_Orden INT NOT NULL,
  fk_idComanda INT NOT NULL,
  PRIMARY KEY (idMesa),
  CONSTRAINT idComanda
    FOREIGN KEY (fk_idComanda)
    REFERENCES Comanda (idComanda)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX idComanda_idx ON Mesa (fk_idComanda ASC);


-- -----------------------------------------------------
-- Table `cheftable`.`Menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Menu (
  idMenu INT NOT NULL AUTO_INCREMENT,
  Desayuno VARCHAR(45) NOT NULL,
  Almuerzo VARCHAR(45) NOT NULL,
  fk_idPlato INT NOT NULL,
  PRIMARY KEY (idMenu),
  CONSTRAINT fk_idPlato
    FOREIGN KEY (fk_idPlato)
    REFERENCES Plato (idPlato)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX fk_idPlato_idx ON Menu (fk_idPlato ASC);


-- -----------------------------------------------------
-- Table `cheftable`.`Ingrediente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Ingrediente (
  idIngrediente INT NOT NULL AUTO_INCREMENT,
  Lacteos VARCHAR(45) NOT NULL,
  Carnicos VARCHAR(45) NOT NULL,
  Granos VARCHAR(45) NOT NULL,
  Vegetales VARCHAR(45) NOT NULL,
  Bebidas VARCHAR(45) NOT NULL,
  Especias VARCHAR(45) NOT NULL,
  PRIMARY KEY (idIngrediente))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cheftable`.`Plato-Ingrediente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Plato_Ingrediente (
  Fecha DATE NOT NULL,
  Precio INT NOT NULL,
  fk_idPlato INT NOT NULL,
  fk_idIngrediente INT NOT NULL,
  PRIMARY KEY (Fecha),
 
    FOREIGN KEY (fk_idPlato)
    REFERENCES Plato (idPlato)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
 
    FOREIGN KEY (fk_idIngrediente)
    REFERENCES Ingrediente (idIngrediente)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX fk_idPlato_idx ON Plato_Ingrediente (fk_idPlato ASC);

CREATE INDEX fk_idIngrediente_idx ON Plato_Ingrediente (fk_idIngrediente ASC);


-- -----------------------------------------------------
-- Table `cheftable`.`Cheft`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Cheft (
  idChef INT NOT NULL AUTO_INCREMENT,
  Nombre_chef VARCHAR(45) NOT NULL,
  Celular VARCHAR(45) NOT NULL,
  Password VARCHAR(45) NOT NULL,
  fk_idMenu INT NOT NULL,
  fk_idIngrediente INT NOT NULL,
  PRIMARY KEY (idChef),
  CONSTRAINT fk_idMenu
    FOREIGN KEY (fk_idMenu)
    REFERENCES Menu (idMenu)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_idIngrediente
    FOREIGN KEY (fk_idIngrediente)
    REFERENCES Ingrediente (idIngrediente)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX fk_idMenu_idx ON Cheft (fk_idMenu ASC);

CREATE INDEX fk_idIngrediente_idx ON Cheft (fk_idIngrediente ASC);


-- -----------------------------------------------------
-- Table `cheftable`.`Ingrediente-Administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Ingrediente_Administrador (
  Stock INT NOT NULL,
  fk_idIngrediente INT NOT NULL,
  fk_idAdministrador INT NOT NULL,
  PRIMARY KEY (Stock))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cheftable`.`Proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Proveedor (
  idProveedor INT NOT NULL AUTO_INCREMENT,
  Nombre_prov VARCHAR(45) NOT NULL,
  Direccion VARCHAR(45) NOT NULL,
  Celular VARCHAR(45) NOT NULL,
  Tipo_prov VARCHAR(45) NOT NULL,
  PRIMARY KEY (idProveedor))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cheftable`.`Administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Administrador (
  idAdministrador INT NOT NULL AUTO_INCREMENT,
  Nombre VARCHAR(45) NOT NULL,
  Celular VARCHAR(45) NOT NULL,
  Password VARCHAR(45) NOT NULL,
  fk_idProveedor INT NOT NULL,
  fk_Codigo INT NOT NULL,
  PRIMARY KEY (idAdministrador),
  CONSTRAINT fk_Codigo
    FOREIGN KEY (fk_Codigo)
    REFERENCES Cierre (Codigo)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_idProveedor
    FOREIGN KEY (fk_idProveedor)
    REFERENCES Proveedor (idProveedor)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX fk_Codigo_idx ON Administrador (fk_Codigo ASC);

CREATE INDEX fk_idProveedor_idx ON Administrador (fk_idProveedor ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;